# Generated by Django 4.2.7 on 2024-07-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Course', max_length=255)),
                ('overview', models.TextField(default='No overview provided.')),
                ('category', models.CharField(choices=[('Web Management', 'Web Management'), ('Business Administration', 'Business Administration'), ('Graphic Design', 'Graphic Design'), ('Marketing', 'Marketing'), ('Health & Fitness', 'Health & Fitness'), ('Information Software', 'Information Software'), ('Software Engineering', 'Software Engineering'), ('History & Archeologic', 'History & Archeologic'), ('Computer Science', 'Computer Science'), ('Art & Design', 'Art & Design'), ('UI/UX Design', 'UI/UX Design')], default='Web Management', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('duration', models.CharField(default='00:00', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=10)),
                ('video_link', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('notes_link', models.FileField(blank=True, null=True, upload_to='files/')),
                ('free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('expiry_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lessons', models.ManyToManyField(related_name='sections', to='api.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.curriculumsection'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.review'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
