# Generated by Django 4.2.7 on 2024-07-20 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Web Management', 'Web Management'), ('Business Administration', 'Business Administration'), ('Graphic Design', 'Graphic Design'), ('Marketing', 'Marketing'), ('Health & Fitness', 'Health & Fitness'), ('Information Software', 'Information Software'), ('Software Engineering', 'Software Engineering'), ('History & Archeologic', 'History & Archeologic'), ('Computer Science', 'Computer Science'), ('Art & Design', 'Art & Design'), ('UI/UX Design', 'UI/UX Design')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
