# Generated by Django 4.2.7 on 2024-07-26 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scheduledsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsession',
            name='student',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
